### ISSUE TITLE
Update an existing Adaptive Card action doesn't work on prompts

### ISSUE THREAD

**Issue by stephanbisser** [microsoft/botframework-components#1276] opened 2021-11-05 12:41 UTC
## Describe the bug

When you create a new AC using the `Create an Adaptive Card` action and then use that AC in a prompt, you cannot update the AC using `Update an existing Adaptive Card action`, as you will always get the error:

`UpdateAdaptiveCard('={"type": "AdaptiveCard"...'): a valid 'ActivityId' wasn't provided.`

## Version

Composer Release: 2.1.1-nightly.274508.6d2b695
SDK: 4.12.0

## To Reproduce

Use the following logic within a dialog/trigger:

```
{
  "$kind": "Microsoft.AdaptiveDialog",
  "$designer": {
    "name": "DemoBot",
    "description": "",
    "id": "A79tBe"
  },
  "autoEndDialog": true,
  "defaultResultProperty": "dialog.result",
  "triggers": [
    {
      "$kind": "Microsoft.OnConversationUpdateActivity",
      "$designer": {
        "id": "376720"
      },
      "actions": [
        {
          "$kind": "Microsoft.Foreach",
          "$designer": {
            "id": "518944",
            "name": "Loop: for each item"
          },
          "itemsProperty": "turn.Activity.membersAdded",
          "actions": [
            {
              "$kind": "Microsoft.IfCondition",
              "$designer": {
                "id": "641773",
                "name": "Branch: if/else"
              },
              "condition": "string(dialog.foreach.value.id) != string(turn.Activity.Recipient.id)",
              "actions": [
                {
                  "$kind": "Microsoft.SendActivity",
                  "$designer": {
                    "id": "859266",
                    "name": "Send a response"
                  },
                  "activity": "${SendActivity_Greeting()}"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "$kind": "Microsoft.OnUnknownIntent",
      "$designer": {
        "id": "mb2n1u"
      },
      "actions": [
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "lqjUYo"
          },
          "activity": "${SendActivity_lqjUYo()}"
        },
        {
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "ftpMBV"
          },
          "property": "dialog.propID",
          "value": "=turn.lastresult.id"
        },
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "RCQqw8"
          },
          "disabled": false,
          "maxTurnCount": 3,
          "alwaysPrompt": false,
          "allowInterruptions": false,
          "unrecognizedPrompt": "",
          "invalidPrompt": "",
          "defaultValueResponse": "",
          "prompt": "${TextInput_Prompt_RCQqw8()}",
          "property": "turn.result"
        },
        {
          "$kind": "Microsoft.UpdateActivity",
          "$designer": {
            "id": "pqGSW4"
          },
          "activityId": "=dialog.propID",
          "activity": "${UpdateActivity_Activity_pqGSW4()}"
        }
      ]
    },
    {
      "$kind": "Microsoft.OnIntent",
      "$designer": {
        "id": "9bfYSA",
        "name": "update"
      },
      "intent": "update",
      "actions": [
        {
          "$kind": "Microsoft.Bot.Components.CreateAdaptiveCard",
          "$designer": {
            "id": "SyCgUQ"
          },
          "template": {
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.2",
            "type": "AdaptiveCard",
            "body": [
              {
                "type": "TextBlock",
                "text": "default text",
                "weight": "bolder",
                "isSubtle": false
              }
            ]
          },
          "resultProperty": "dialog.card"
        },
        {
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "koAT1B"
          },
          "property": "dialog.cID",
          "value": "=turn.lastresult.id"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "uiFAbT"
          },
          "activity": "${SendActivity_uiFAbT()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "P4pvGI"
          },
          "activity": "${SendActivity_P4pvGI()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "r9NrVD"
          },
          "activity": "${SendActivity_r9NrVD()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "29Ngnr"
          },
          "activity": "${SendActivity_29Ngnr()}"
        },
        {
          "$kind": "Microsoft.SetProperty",
          "$designer": {
            "id": "401AOq"
          },
          "value": "=turn.activity.id",
          "property": "dialog.cardID"
        },
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "fMCffc"
          },
          "disabled": false,
          "maxTurnCount": 3,
          "alwaysPrompt": false,
          "allowInterruptions": false,
          "unrecognizedPrompt": "",
          "invalidPrompt": "",
          "prompt": "${TextInput_Prompt_fMCffc()}",
          "property": "turn.answer"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "RWh2d5"
          },
          "activity": "${SendActivity_RWh2d5()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "F6qJ6q"
          },
          "activity": "${SendActivity_F6qJ6q()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "YuWayA"
          },
          "activity": "${SendActivity_YuWayA()}"
        },
        {
          "$kind": "Microsoft.SendActivity",
          "$designer": {
            "id": "uIQVa0"
          },
          "activity": "${SendActivity_uIQVa0()}"
        },
        {
          "$kind": "Microsoft.Bot.Components.UpdateAdaptiveCard",
          "$designer": {
            "id": "z9YM24",
            "name": "Update an existing Adaptive Card"
          },
          "template": {
            "type": "AdaptiveCard",
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.2",
            "body": [
              {
                "type": "TextBlock",
                "text": "default text v2",
                "weight": "bolder",
                "isSubtle": false
              }
            ]
          },
          "activityId": "=dialog.cID"
        }
      ]
    },
    {
      "$kind": "Microsoft.OnIntent",
      "$designer": {
        "id": "bgOh3Q",
        "name": "test"
      },
      "intent": "test",
      "actions": [
        {
          "$kind": "Microsoft.Bot.Components.CreateAdaptiveCard",
          "$designer": {
            "id": "Bl0wYD"
          },
          "template": {
            "type": "AdaptiveCard",
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.2",
            "body": [
              {
                "type": "TextBlock",
                "text": "default text",
                "weight": "bolder",
                "isSubtle": false
              }
            ]
          },
          "resultProperty": "dialog.card"
        },
        {
          "$kind": "Microsoft.TextInput",
          "$designer": {
            "id": "PZ9cHQ"
          },
          "disabled": false,
          "maxTurnCount": 3,
          "alwaysPrompt": false,
          "allowInterruptions": false,
          "unrecognizedPrompt": "",
          "invalidPrompt": "",
          "defaultValueResponse": "",
          "prompt": "${TextInput_Prompt_PZ9cHQ()}",
          "property": "user.input"
        },
        {
          "$kind": "Microsoft.Bot.Components.UpdateAdaptiveCard",
          "$designer": {
            "id": "qJADQy"
          },
          "template": {
            "type": "AdaptiveCard",
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.2",
            "body": [
              {
                "type": "TextBlock",
                "text": "default text updated",
                "weight": "bolder",
                "isSubtle": false
              }
            ]
          },
          "activityId": "=turn.activity.replyToId"
        }
      ]
    }
  ],
  "generator": "DemoBot.lg",
  "id": "DemoBot",
  "recognizer": "DemoBot.lu.qna"
}
```

## Expected behavior

It should be possible to use an Adaptive Card within a prompt and update that same card after the user has answered the prompt.

**Comment by ryanlengel** [comment] 2021-11-08 20:35
Hi @stephanbisser!

Two things that stick out to me immediately:
1. The Adaptive Cards package is compatible with SDK 4.13.1 and above, you'll need to upgrade your SDK.
2. The Teams channel is the only one where updating existing Adaptive Cards is supported, it's expected to not work on other channels. If you are testing this on Web Chat it will not work.

**Comment by stephanbisser** [comment] 2021-11-08 21:19
Hi @ryanlengel thanks for you response. 
How do I update the SDK version in Composer?
I'm testing only in the Teams channel so that should be fine

**Comment by ryanlengel** [comment] 2021-11-11 18:04
Based on the SDK v4.12 referenced I believe that you created your bot on Composer on a 1.x revision, instructions for converting to the adaptive runtime (SDK v4.13+) are available at https://docs.microsoft.com/en-us/composer/how-to-migrate-bot-to-2-0.

**Comment by stephanbisser** [comment] 2021-11-11 18:43
Sorry but no. I'm using Composer in the nightly build version as stated in the issue description (please see above) so I'm definitely using Composer 2.x. So is the SDK update the same process for 2.x based bots?

**Comment by ryanlengel** [comment] 2021-11-11 20:43
You must manually update the SDK references in your bot's project.

If you have Visual Studio:
1. Open the .sln file
![image](https://user-images.githubusercontent.com/43043272/141364667-fc3d7e84-a9ab-483d-89ac-3a3710123b5c.png)
2. Right-click on the bot project and select **Manage NuGet Packages**
![image](https://user-images.githubusercontent.com/43043272/141364801-20a558b8-e891-45d0-b503-f2bc26c387bb.png)
3. Under **Update** you can update all Microsoft.Bot.Builder packages to the latest SDK.

If you don't have Visual Studio, you can manually edit your .csproj file.
1. Open the .csproj file
2. Update the SDK versions to `4.14.1` (latest)
![image](https://user-images.githubusercontent.com/43043272/141366127-2624055f-ad45-4db9-807e-562036039098.png)

**Comment by stephanbisser** [comment] 2021-11-15 09:13
SDK version updated to 4.14.1 but unfortunately with the same result:

`UpdateAdaptiveCard('={ "type": "AdaptiveCard"...')2: a valid 'ActivityId' wasn't provided.`

The dialog looks as follows:

![image](https://user-images.githubusercontent.com/29750798/141754231-5975adfd-d9fc-4aa7-af9d-1260cb52e6fa.png)

So what's the process of udpating an Adaptive Card within a prompt? Please assist here @ryanlengel, thanks

**Comment by stephanbisser** [comment] 2021-11-17 19:48
@ryanlengel do you have any ideas on how to solve this issue here already please?

**Comment by stephanbisser** [comment] 2021-11-24 06:51
@clearab are you maybe able to assist me here? I unfortunately haven't figured out how to solve this issue by now

**Comment by ryanlengel** [comment] 2021-11-29 19:13
@Stevenic, any guidance on how to use the "update an existing Adaptive Card" action within a prompt?

**Comment by clearab** [comment] 2021-11-30 06:51
The Activity ID field in the update an existing Adaptive Card action needs a valid ActivityID for the card. My guess is the prompt is causing Teams to do its crazy message splitting thing, which is leading to this happening. If you send the card using the "Send an Adaptive Card" action, do you get a valid Activity ID back you can use (that is the way this was intended to work)

I'd suggest trying to re-architect the conversation around not sending the AC in a prompt if possible (maybe a text field and a submit button instead, then add a trigger for the invoke?). If that isn't possible, @ryanlengel or @Stevenic do either of you know how to get the necessary Activity ID out of the prompt message send?

**Comment by gabog** [comment] 2021-12-10 19:42
Hi @stephanbisser, let us know if @clearab comment helped. I will close this one for now, feel free to re-open if it is still an issue.

**Closed by gabog** 2021-12-10 19:42 UTC
Labels: customer-reported, customer-replied-to, bug

**Comment by stephanbisser** [comment] 2021-12-13 22:27
Sorry for the late reply, but I'd really need a solution to make this work in a prompt as otherwise I would need to add a lot of triggers for the invoke buttons of various cards. @ryanlengel or @Stevenic could you maybe propose a solution to make this work as @clearab suggested? Thanks

**Comment by clearab** [comment] 2021-12-16 19:14
You would always need to add triggers to handle the invokes - they come in as separate activities and shouldn't count as a message coming back from the prompt. If you wanted them to work w/o having to handle invokes, you'd need to turn them into messageBack actions - [doc](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=json#adaptive-cards-with-messageback-action)

In Teams, the recommended method for making the in-place update of the card to work is to use action.execute actions - with triggers for the incoming invokes that reply to the invoke with a new adaptive card. [Doc](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?tabs=mobile)
