### ISSUE TITLE
Null Reference Exception coming every time on call of any dialog for who skill in composer

### ISSUE THREAD

**Issue by RajdeepRay0411** [microsoft/botframework-components#463] opened 2020-12-11 07:31 UTC
## Describe the bug

Null Reference Exception coming every time on call of any dialog for who skill in the composer though Luis is triggering the correct flow according to the intent.

## Version

Bot Framework Composer (v 1.2.1)

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. Download the solution for who skill from Github.
2. Run the application in the composer.
3. Trigger any intent(For example Whois)
4. Throwing exception "Object reference not set to an instance of an object."

## Expected behavior

A respective dialog should be initiated according to the intent triggered.

## Screenshots

![image](https://user-images.githubusercontent.com/51920866/101875348-78172e00-3bb0-11eb-96ef-1f56d12a83c2.png)

**Comment by gabog** [comment] 2021-01-05 14:49
Reassigning to @thomas-chung that can provide further guidance.

**Comment by thomas-chung** [comment] 2021-01-07 21:11
Hi @RajdeepRay0411 it appears you have engaged one of our fellow engineers in our channels. Would you be okay with us closing this issue and continue through the other channel?

**Comment by thomas-chung** [comment] 2021-01-08 09:33
Hi @RajdeepRay0411! Since you have mentioned the issue is resolved in the other channel we are going to close this issue. Thanks for engaging us!

**Closed** 2021-01-08 09:33 UTC
Labels: Bot Services, customer-replied-to, customer-reported
