### ISSUE TITLE
People Skill - Adaptive card list size is fixed to 16

### ISSUE THREAD

**Issue by ryub3n** [microsoft/botframework-components#1337] opened 2022-05-20 19:15 UTC
## Describe the bug

The People skill doesn't show the names of other people if they exceed 16 in number. Sometimes the name is not in the list of the 16 items returned especially when it's a common name.

## Version

Version: 2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Create the Enterprise Assistant with Calendar and People Skills
2. Ask a people related quesion and make sure to use the most common name with more than 16 entries e.g. John
3. The Adaptive card sent has a max list of **16** items

## Expected behavior

Expected to see beyond 16 items especially if the user isn't in the list

**Comment by ramfattah** [comment] 2022-05-24 19:49
investigating

**Comment by ramfattah** [comment] 2022-06-03 22:05
@ryub3n thank you for your patience; we are investigating this one.

**Comment by ramfattah** [comment] 2022-06-06 18:52
Hi @ryub3n 

Looks like this is by design and not a bug. In [GetPeersDialog.dialog](https://github.com/microsoft/botframework-components/blob/main/generators/generator-bot-enterprise-people/generators/app/templates/dialogs/GetPeersDialog/GetPeersDialog.dialog), `maxCount` is set to 15.

https://github.com/microsoft/botframework-components/blob/566ada6adc20078a32e81d7ade26776b944323a3/generators/generator-bot-enterprise-people/generators/app/templates/dialogs/GetPeersDialog/GetPeersDialog.dialog#L148

**Comment by ramfattah** [comment] 2022-06-06 18:55
Closing this issue. @ryub3n, please feel free to re-open if needed.

**Closed by ramfattah** 2022-06-06 18:55 UTC
Labels: customer-reported, bug, Bot Services
