### ISSUE TITLE
have template generators pass options through to runtime generator

### ISSUE THREAD

**Issue by pavolum** [microsoft/botframework-components#601] opened 2021-02-20 02:45 UTC
Composer now passes users selection for runtime language (js/csharp) and runtime type (webapp/functions) down to the template generator. The template generators need to then send those options down to the adaptive runtime generator ensuring that all future options trickle down to the runtime

- [ ] Update all r13 template generators to pass flag through to runtime generator.
- [ ] Test new generator in Composer and create any issues if current runtime template plugin has issues with the build process for the functions runtime

**Comment by peterinnesmsft** [comment] 2021-02-22 20:12
Is this a dupe of https://github.com/microsoft/BotFramework-Composer/issues/5556?

**Comment by peterinnesmsft** [comment] 2021-03-02 18:03
@pavolum this appears to be a duplicate of https://github.com/microsoft/BotFramework-Composer/issues/5556 - can you confirm?

**Comment by pavolum** [comment] 2021-03-18 17:21
Man I need to set up gitHub alerts better,

This is not a duplicate but it is being handled by Joshs PR here https://github.com/microsoft/botframework-components/pull/746/files#diff-284da5283bb39b7c7d6939fe6454cd6557b644a540f2d3c9adb80549d6a51970R16

**Closed** 2021-03-22 16:20 UTC
Labels: Area: Generators, Size: S, feature-request, needs-triage
