### ISSUE TITLE
Calendar Skill - GetEventAttendees intent not responding as expected

### ISSUE THREAD

**Issue by ryub3n** [microsoft/botframework-components#1339] opened 2022-05-20 19:32 UTC
## Describe the bug

The getEventAttendess intent doesn't provide the list of users who have accepted/declined the invite.

## Version

Version: 2.1.2
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## To Reproduce

1. Create the Enterprise Assistant with Calendar and People Skills
2. Make sure you have a meeting where you are the organizer with some attendees.
3. Ask the bot 'did anyone respond to my invite?'
4. Select the invite from the list
5. It just shows the meeting card but doesn't show **all** who accepted/declined the invite

## Expected behavior

A meeting summary adaptive card should be displaued showing the list of attendees and their reponse to the invite i.e. accepted/declined.

**Comment by ramfattah** [comment] 2022-05-24 19:49
investigating

**Comment by ramfattah** [comment] 2022-06-01 23:16
Hello @ryub3n, Thank you for your patience. We are investigating and will get back to you once we have updates.

**Comment by ramfattah** [comment] 2022-06-03 01:45
Hi @ryub3n,

After sending `did anyone respond to my invite?` to the bot, I received an adaptive card with the meeting information.

Example: adaptive card containing attendees, without acceptance status:
<img src="https://user-images.githubusercontent.com/38049078/171770183-3f04bbe6-1903-4f60-9b45-25195b092191.png" width="600"/>

#

I'm able to repro and investigating further if this is the expected behavior. 
Thanks.

**Comment by ramfattah** [comment] 2022-06-03 02:24
Hi @ryub3n,

I'm able to repro using Composer v 2.1.2 and Dialogs.Adaptive.Runtime v 4.16.0.

#

When using Enterprise Assistant Bot, after sending `did anyone respond to my invite?` to the bot, I received an adaptive card with the meeting information.

Example: adaptive card containing attendees, without acceptance status:
<img src="https://user-images.githubusercontent.com/38049078/171770183-3f04bbe6-1903-4f60-9b45-25195b092191.png" width="600"/>

**Comment by lauren-mills** [comment] 2022-06-06 18:33
Hi @ryub3n this is by design to prevent overcrowding the card. You should be able to view the attendee status in the results from the Graph API in the graph action and modify this card to fit your specific needs. The templates are fully customizable so you can change the responses as you see fit.

**Comment by ramfattah** [comment] 2022-06-06 18:59
Thank you for verifying @lauren-mills. 

Closing as this is not a bug. @ryub3n please feel free to re-open if needed.

**Closed by ramfattah** 2022-06-06 18:59 UTC
Labels: customer-reported, bug, Bot Services

**Comment by lauren-mills** [comment] 2022-06-06 19:22
The getEventAttendees intent doesn't show accepted and declined responses, just who was invited. The LUIS intent may have routed to that intent, but it doesn't mean that feature is supported. If you want to update the intent triggering to explicitly not support this case, you would want to add your utterance to the 'None' intent training.

However, I would go in and update the existing card to maybe change the color of the attendee name based on the value of the status for that user. We are not actively making these sorts of experience changes to these templates, only bug fixes.

**Comment by ryub3n** [comment] 2022-06-06 19:48
This utterance is part of getEventAttendees hence the confusion.
https://github.com/microsoft/botframework-components/blob/566ada6adc20078a32e81d7ade26776b944323a3/generators/generator-bot-enterprise-calendar/generators/app/templates/language-understanding/en-us/Calendar/getEventAttendees.en-us.lu#L2
Also,
https://github.com/microsoft/botframework-components/blob/566ada6adc20078a32e81d7ade26776b944323a3/generators/generator-bot-enterprise-calendar/generators/app/templates/language-understanding/en-us/Calendar/getEventAttendees.en-us.lu#L5

Thanks for clarifying I will remove the utterances that don't belong.

**Comment by jasonyazell** [comment] 2022-06-07 12:28
Most, if not all triggers in getEventAttendees is based on pulling who is attending, not who is invited. Can you please give more information on why this trigger is working properly and not a big as it is getEventAttendees not getEventInvites?
