### ISSUE TITLE
Default bot name for Basic Conversational template is still conversational_core

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-components#996] opened 2021-04-25 12:38 UTC
## Describe the bug
Default bot name for Basic Conversational template is still conversational_core.

## Expected behavior
We should change this to something more aligned with the template name.  We should probably also make it Pascal Case and remove any special chars too (i.e. the underscore), since the name of the bot will drive the namespaces and conversational_core looks really odd (at least in C#).

## Screenshots
![image](https://user-images.githubusercontent.com/3900649/115993527-286b5900-a5cb-11eb-92e7-fe5e597170f3.png)

**Comment by clearab** [comment] 2021-04-25 23:51
Tracking here: https://github.com/microsoft/botframework-components/issues/996

**Comment by peterinnesmsft** [comment] 2021-04-27 18:39
Closing as duplicate of https://github.com/microsoft/BotFramework-Composer/issues/7424.

**Closed by peterinnesmsft** 2021-04-27 18:39 UTC
Labels: bug, needs-triage
