### ISSUE TITLE
Teams component, @mentions not being processed correctly

### ISSUE THREAD

**Issue by SOE-YoungS** [microsoft/botframework-components#1480] opened 2023-03-10 19:00 UTC
Using the Teams component, how can I handle @mentions?

I've implemented !Commands as intents, but these aren't correctly triggering when called with "@bot !Command".

Can I get an example of how the component should be handling @mentions please?

**Comment by ramfattah** [comment] 2023-03-13 16:45
Hi @SOE-YoungS , i'm investigating.

**Comment by SOE-YoungS** [comment] 2023-03-13 17:14
@ramfattah Thanks!

For the minute I've added a workaround by adding a "set property" action to "replace @{Bot Name}" in "turn.recognised.text in any triggers with "- !Command" intents that I need.

Ideally, I believe this should be done at a code level though, I just can't see where I can inject it.

FYI: I'm using the Core Bot with Language template via an Azure Function App.
I have also added the Microsoft.Bot.Components.Teams (1.4.0) package.

**Comment by ramfattah** [comment] 2023-04-07 17:36
Hi @SOE-YoungS,

I apologize for the delay in resolving this issue. I've been having some difficulty setting up the same project as yours, which has been hindering my progress in finding a solution.

**To help expedite the process and allow me to better understand the issue you're facing, could you please provide a minimal reproducible .zip project that demonstrates the problem? This will help me in setting up the project correctly and allow me to more effectively investigate the issue.**

To create a minimal reproducible project, please include only the essential code and components needed to showcase the issue, removing any unnecessary or sensitive information.

Once you've prepared the .zip project, you can attach it to your response here or upload it to a file-sharing service and provide a link to the file. Your cooperation will be greatly appreciated, and it will help me address your concerns more quickly.

Thank you for your understanding and assistance.

**Comment by ramfattah** [comment] 2023-05-09 21:59
Closing due to inactivity.

**Closed by ramfattah** 2023-05-09 21:59 UTC
Labels: customer-reported, Bot Services
