### ISSUE TITLE
Bot Framework Composer can't retrive entities with microsoft.bot.components.recognizers.clurecognizer V1.0.1 library

### ISSUE THREAD

**Issue by Symon94** [microsoft/botframework-components#1546] opened 2023-12-06 13:45 UTC
## Describe the bug
In Bot Framework Composer, after installing microsoft.bot.components.recognizers.clurecognizer V1.0.1 library for CLU, the bot doesn't recognize some entities if the language is different to en-US .
So I search in the source code provided here and I think that I found a bug.

![Screenshot (132)](https://github.com/microsoft/botframework-components/assets/124156685/78d32969-13cf-4ceb-b39f-0336c470d840)

In the image above, I show where the bug is. I change that portion of code adding a field "language" = "it". 
After restarting the Bot Framework Composer, bot manages to capture entities correctly for the chosen language.
I think it is possible to be able to retrieve the language using the DialogContext property Locale

## Version
Release: 2.1.3-nightly.364675.1a93f21
SDK runtime packages:
4.12.0

## To Reproduce
- Open Bot Framework Composer and run it
- Open the emulator and ask something to the bot
- no entity was captured in the response given by the turn as in the image below

![Screenshot (133)](https://github.com/microsoft/botframework-components/assets/124156685/709d6306-f638-49f0-a9be-c9949086cc82)

## Expected behavior
I expect the captured entities to be in the entities field

**Comment by rampaged** [comment] 2024-01-14 09:57
hi @Symon94, 

I'm not able to reproduce this issue. 

In dotnet composer bot, I added multiple languages support such as Italian ("it") and German ("de"). In both of these languages the `entities` were captured from CLU.

Here are the steps I took:
1. [Created CLU](https://learn.microsoft.com/en-us/azure/ai-services/language-service/conversational-language-understanding/quickstart?pivots=language-studio) in Language studio and deployed a model.

![CLU_Schema](https://github.com/microsoft/botframework-components/assets/38049078/735c5336-a2ac-43f3-acb3-a7c30a99541d)

![Data_Labeling](https://github.com/microsoft/botframework-components/assets/38049078/30c4fd5c-06df-4714-a472-498554e01e02)

2. [Added Multiple languages](https://learn.microsoft.com/en-us/composer/how-to-use-multiple-language?tabs=v2x) to Composer

3. Install [ConversationLanguageUnderstanding](https://github.com/microsoft/botframework-components/tree/main/packages/Recognizers/ConversationLanguageUnderstanding/dotnet) V1.0.1 package in Composer and configure the main dialog for custom CLU recognizer.

4. In "Unknown intent" trigger, I added the following response:

![Screenshot from 2024-01-14 01-50-50](https://github.com/microsoft/botframework-components/assets/38049078/6da4663c-4847-46e2-8b0c-6e5b8895b886)

4. In Emulator, change locale. From my end I tested with "it" and "de".

5. Send an utterance to the bot 

6. Entities is captures in different language:

![em](https://github.com/microsoft/botframework-components/assets/38049078/7a6af59b-4e7c-483a-9a6a-8edb08b7e710)


```json
{
  "lgType": "Activity",
  "text": {
    "text": "order pizza",
    "alteredText": null,
    "intents": {
      "OrderPizza": {
        "score": 0.9621253
      }
    },
    "entities": {
      "$instance": {},
      "order": [
        {
          "category": "order",
          "text": "order",
          "offset": 0,
          "length": 5,
          "confidenceScore": 1
        }
      ],
      "pizza": [
        {
          "category": "pizza",
          "text": "pizza",
          "offset": 6,
          "length": 5,
          "confidenceScore": 1
        }
      ]
    },
    "intent": "OrderPizza",
    "score": 0.9621253
  }
}


```

**Comment by dmvtech** [comment] 2024-07-12 21:02
Closing due to inability to reproduce or confirm a bug.

**Closed by dmvtech** 2024-07-12 21:02 UTC
Labels: needs-triage, bug
