### ISSUE TITLE
calendar-assistant forgets I am talking to the calendar skill

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-components#660] opened 2021-03-02 06:16 UTC
## Version
Latest calendar-assistant generator as of 3/2/21

## Describe the bug
I am unable to stick to a conversation with the calendar skill in a bot generated using the calendar-assistant. The bot seems to fall back to the cancel intent in the root (or some other intent, not sure).

## To Reproduce
1. Create a new calendar-assistant multibot.
2. Configure LUIS, AppId, PWD and AllowedCallers in parent and calendar skill
3. Configure OAuth connection in calendar skill
4. Start parent and skill
5. Say `Create an event`
6. Sign in
7. Say `Demo my bug`
8. The bot will respond `Got it. I'll stop here'

![image](https://user-images.githubusercontent.com/12264946/109606560-d5a68100-7af4-11eb-85a3-d1e88884308a.png)

## Expected behavior
I would expect to be able to complete the skill task.

**Comment by ryanlengel** [comment] 2021-03-03 22:26
There may be two issues here:
- Calendar skill should maintain control of the conversation
- Conversation core root bot has imbalanced LU, tracking at #683

**Comment by lauren-mills** [comment] 2021-03-22 19:58
Looks like it just detected your utterances as a cancel utterance

**Comment by ryanlengel** [comment] 2021-03-22 20:01
@lauren-mills we've updated the core LU models now, you can verify when we setup Enterprise Assistant with Assistant Core

**Comment by peterinnesmsft** [comment] 2021-04-05 19:20
@gabog to confirm fixes meet satisfaction and close as appropriate.

**Comment by lauren-mills** [comment] 2021-04-05 20:08
Confirmed fixed in RC2

**Closed by lauren-mills** 2021-04-05 20:08 UTC
Labels: Area: Generators, bug, needs-triage

**Comment by lauren-mills** [comment] 2021-04-05 20:10
![image](https://user-images.githubusercontent.com/27976702/113621209-381d0080-9610-11eb-9f50-05bbe39fdb57.png)
