### ISSUE TITLE
People Skill sending  turn.items error to the user

### ISSUE THREAD

**Issue by ryub3n** [microsoft/botframework-components#1323] opened 2022-04-13 15:16 UTC
## Describe the bug

People Skill sending  turn.items error to the user if the user doesn't select a choice from the list of choices

## Version

Composer version 2.1.2
SDK version 4.15.2

## To Reproduce

1. Create the Enterprise Assistant with Calendar and People Skills.
2. Enter 'Who is Priya's manager?' (or any common name e.g. John)
3. It will return a card with a list of entries since it's not able to find a unique user
4. Instead of selecting a user, interrupt the bot by sending 'Who is John's manager?' 
5. The bot will send a message with the error shown below in the screenshots

## Expected behavior

It should force the user to select a user from the list.

## Screenshots

<img width="395" alt="image" src="https://user-images.githubusercontent.com/24279903/163212022-be05bb1c-e722-4e1d-9329-9cc6a8fca83c.png">

**Comment by ramfattah** [comment] 2022-04-15 18:41
Hello @ryub3n - I'm investigating this.

**Comment by ramfattah** [comment] 2022-04-20 17:25
@ryub3n,

I'm not able to reproduce this issue,.
#

Sharing my video demo steps:
[![Image from Gyazo](https://i.gyazo.com/9cd9ded134221284e1dad6e071d0d1b1.gif)](https://gyazo.com/9cd9ded134221284e1dad6e071d0d1b1)

It seems I'm getting this error `Operation returned an invalid status code ‘BadRequest’` after interrupting the bot by sending 'Who is John's manager?' https://github.com/microsoft/botframework-components/issues/1319

@ryub3n, Am I missing something from my end? Any additional steps I shall add to reproduce your issue?

**Comment by bensonjm** [comment] 2022-04-20 17:55
@ramfattah , I think this error occurs only after you deploy the bot and use webchat because even I'm not able to reproduce it using emulator.
Additional context: Our bot is hosted on a SharePoint site and uses Bot Framework WebChat

**Comment by ryub3n** [comment] 2022-04-20 17:59
@ramfattah , I think this error occurs only after you deploy the bot and use webchat because even I'm not able to reproduce it using emulator.
Additional context: Our bot is hosted on a SharePoint site and uses Bot Framework WebChat

**Comment by ramfattah** [comment] 2022-04-20 19:25
Hey @ryub3n 

Thanks for following up. There is a PR for this and it's currently being worked on https://github.com/microsoft/botframework-components/pull/1326

**Comment by ramfattah** [comment] 2022-04-20 19:31
@ryub3n 

Thanks, I will try again in WebChat this time and report back.

**Comment by ramfattah** [comment] 2022-04-20 20:45
@ryub3n 

Update: I was able to reproduce this issue in WebChat.

Here are the steps I took:
* Created and deployed an Enterprise Assistant Template from the following documentation https://docs.microsoft.com/en-us/composer/templates/enterprise-assistant-tutorial
* After the bot is published and OAuths have been configured for the skills, In Azure, I created a `Direct Line` channel for the Assistant bot (Root bot)
* Cloned the [/k.direct-line-token/](https://github.com/microsoft/BotFramework-WebChat/tree/main/samples/01.getting-started/k.direct-line-token) webchat sample and provided my Direct Line secret in .env file
* I followed the customer's [steps to reproduce](https://github.com/microsoft/botframework-components/issues/1323#:~:text=Create%20the%20Enterprise,in%20the%20screenshots)
* I get the same error as the customer when I type `Who is John's manager` the second time.

#

![image](https://user-images.githubusercontent.com/38049078/164316781-7caeadbf-927f-4923-9487-9f9f00554398.png)

<details>
  <summary>View full error message</summary>
  
``` 
ListDialog.en-us.lg:turn.items must be a string or list. 
[InitialChoicePrompt] Error occurred when evaluating ‘attachments=${json(ListCard(count(turn.items), $pageSize, turn.pageItems, $templates.icon, $templates.title, $templates.item, $pageIndex + 1, $pageCount))}’. 
[ChoiceInput_Prompt_VygDK3] Condition ‘${$turnCount == 1}’: Error occurred when evaluating ‘-${InitialChoicePrompt()}’. [__temp__10b4c53b9e084bfea5fd66b871b943d9] Error occurred when evaluating ‘-${ChoiceInput_Prompt_VygDK3()}’., 
ListDialog.en-us.lg:turn.items must be a string or list. 
[InitialChoicePrompt] Error occurred when evaluating ‘attachments=${json(ListCard(count(turn.items), $pageSize, turn.pageItems, $templates.icon, $templates.title, $templates.item, $pageIndex + 1, $pageCount))}’. [ChoiceInput_Prompt_VygDK3] Condition ‘${$turnCount == 1}’: 
Error occurred when evaluating ‘-${InitialChoicePrompt()}’. [__temp__e1abdd6da8004e8caec63066228c5501] Error occurred when evaluating ‘-${ChoiceInput_Prompt_VygDK3()}’.

```
</details>

**Comment by ramfattah** [comment] 2022-04-23 01:25
closing with PR https://github.com/microsoft/botframework-components/pull/1329

**Closed by ramfattah** 2022-04-23 01:25 UTC
Labels: customer-reported, bug, Bot Services
